#Anno accademico        2012/2013
#Progetto               #1
#Giulio Fornasaro       151991
#Francesco Boschini     151840
#Luca Zamboni           151759
all : 
	mkdir -p /var/log/utility
	chmod 777 /var/log/utility
	gcc -pthread plive.c -o plive -lncurses
